package:
  name: spec2nexus
  version: "2017.3.0"

source:
  git_rev: 2017.3.0
  git_url:  https://github.com/prjemian/spec2nexus.git

build:
  entry_points:
    - spec2nexus = spec2nexus.nexus:main
    - h5toText   = spec2nexus.h5toText:main
    - extractSpecScan = spec2nexus.extractSpecScan:main
    - specplot = spec2nexus.specplot:main
    - specplot_gallery = spec2nexus.specplot_gallery:main

requirements:

  build:
    - python
    - setuptools
    - numpy
    - h5py

  run:
    - python
    - numpy
    - h5py
    - matplotlib

test:

  imports:
    - spec2nexus
    - spec2nexus.spec
    - spec2nexus.eznx
    - spec2nexus.specplot
    - spec2nexus.specplot_gallery


  commands:
    - extractSpecScan --help
    - h5toText --help
    - spec2nexus --help
    - specplot --help
    - specplot_gallery --help


about:
  home: http://spec2nexus.readthedocs.io
  license_file: src/spec2nexus/LICENSE.txt
  license: Creative Commons Attribution 4.0 International Public License
  summary: 'Converts SPEC data files and scans into NeXus HDF5 files'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
# https://conda.io/docs/build_tutorials/pkgs.html
